[Rainmeter]
Update=100
DefaultUpdateDivider=-1


[Metadata]
Name=Network Combination
Author=Peter Han
Information=Displays all network metrics in one
License=Creative Commons BY-NC-SA 4.0
Version=0.4.0


[Variables]
@Include1=#@#comboTemplate.ini
GraphMeasure=NetworkDownload
GraphMeasure2=NetworkUpload
GraphColor=#Yellow#
GraphColor2=#YellowThird#


; MEASURES

[NetworkDownload]
Measure=NetIn
OnUpdateAction=[!UpdateMeter Graph][!UpdateMeter Value]
UpdateDivider=10

[NetworkUpload]
Measure=NetOut
OnUpdateAction=[!UpdateMeter Graph][!UpdateMeter Value2]
UpdateDivider=10


; METERS

[Graph]
LineCount=2
AutoScale=1

[Label]
Text="Network"

[Value]
Text="DL: %1B/s"
; AutoScale automatically appends 'k', 'M', or 'G' based on speed.
AutoScale=1
NumOfDecimals=1

[Value2]
Text="UP: %1B/s"
; AutoScale automatically appends 'k', 'M', or 'G' based on speed.
AutoScale=1
NumOfDecimals=1

[Value3]
Hidden=1
