[Rainmeter]
Update=100
DefaultUpdateDivider=-1


[Metadata]
Name=Network Download
Author=Peter Han
Information=Displays network download rate
License=Creative Commons BY-NC-SA 4.0
Version=0.5.0


[Variables]
@Include1=#@#template.ini
GraphMeasure=NetworkDownload
GraphColor=#Yellow#


; MEASURES

[NetworkDownload]
Measure=NetIn
OnUpdateAction=[!UpdateMeter Graph][!UpdateMeter GraphBackground][!UpdateMeter Value]
UpdateDivider=10


; METERS

[Label]
Text="Network"

[Value]
Text="%1B/s"
; AutoScale automatically appends 'k', 'M', or 'G' based on speed.
AutoScale=1
NumOfDecimals=2


; GRAPHS

[Graph]
AutoScale=1
